pharo-exporting
symbolDefintion
	<preventExport>
    "Auto generated Symbol definition from system/layout/SymbolInitialization.ci
     Use the script at _meta/extractSymbols to generate this method"

    ^ (Array new: 63)
	at: 1 put: #('objectAt:putIfAbsent:' 'SMB_objectAt_putIfAbsent_');
	at: 2 put: #(',' 'SMB__concat');
	at: 3 put: #('=' 'SMB__equal');
	at: 4 put: #('==' 'SMB__pequal');
	at: 5 put: #('&' 'SMB__and');
	at: 6 put: #('apply' 'SMB_apply');
	at: 7 put: #('apply:' 'SMB_apply_');
	at: 8 put: #('asArray' 'SMB_asArray');
	at: 9 put: #('asBoolean' 'SMB_asBoolean');
	at: 10 put: #('asCharacter' 'SMB_asCharacter');
	at: 11 put: #('asSmallInt' 'SMB_asSmallInt');
	at: 12 put: #('asString' 'SMB_asString');
	at: 13 put: #('asSymbol' 'SMB_asSymbol');
	at: 14 put: #('atEnd' 'SMB_atEnd');
	at: 15 put: #('at:' 'SMB_at_');
	at: 16 put: #('at:in:' 'SMB_at_in_');
	at: 17 put: #('at:put:' 'SMB_at_put_');
	at: 18 put: #('basicNew' 'SMB_basicNew');
	at: 19 put: #('basicNew:' 'SMB_basicNew_');
	at: 20 put: #('class' 'SMB_class');
	at: 21 put: #('concat:' 'SMB__concat');
	at: 22 put: #('delete:' 'SMB_delete_');
	at: 23 put: #('/' 'SMB__divide');
	at: 24 put: #('doesNotUnderstand:' 'SMB_doesNotUnderstand_');
	at: 25 put: #('escape:' 'SMB_escape_');
	at: 26 put: #('eval' 'SMB_eval');
	at: 27 put: #('eval:' 'SMB_eval_');
	at: 28 put: #('get:' 'SMB_get_');
	at: 29 put: #('>' 'SMB__gt');
	at: 30 put: #('hash' 'SMB_hash');
	at: 31 put: #('ifFalse:' 'SMB_ifFalse_');
	at: 32 put: #('ifFalse:else:' 'SMB_ifFalse_else_');
	at: 33 put: #('ifTrue:' 'SMB_ifTrue_');
	at: 34 put: #('ifTrue:else:' 'SMB_ifTrue_else_');
	at: 35 put: #('ifTrue:ifFalse:' 'SMB_ifTrue_ifFalse_');
	at: 36 put: #('instVarAt:' 'SMB_instVarAt_');
	at: 37 put: #('instVarAt:put:' 'SMB_instVarAt_put_');
	at: 38 put: #('isNil' 'SMB_isNil');
	at: 39 put: #('isNotNil' 'SMB_isNotNil');
	at: 40 put: #('lookup:' 'SMB_lookup_');
	at: 41 put: #('<' 'SMB__lt');
	at: 42 put: #('-' 'SMB__minus');
	at: 43 put: #('name' 'SMB_name');
	at: 44 put: #('not' 'SMB_not');
	at: 45 put: #('!=' 'SMB__notEqual');
	at: 46 put: #('on:' 'SMB_on_');
	at: 47 put: #('|' 'SMB__or');
	at: 48 put: #('+' 'SMB__plus');
	at: 49 put: #('read' 'SMB_read');
	at: 50 put: #('readAll' 'SMB_readAll');
	at: 51 put: #('rewind' 'SMB_rewind');
	at: 52 put: #('set' 'SMB_set');
	at: 53 put: #('<<' 'SMB__shiftLeft');
	at: 54 put: #('>>' 'SMB__shiftRight');
	at: 55 put: #('size' 'SMB_size');
	at: 56 put: #('*' 'SMB__times');
	at: 57 put: #('update' 'SMB_update');
	at: 58 put: #('value:' 'SMB_value_');
	at: 59 put: #('whileFalse:' 'SMB_whileFalse_');
	at: 60 put: #('whileNil:' 'SMB_whileNil_');
	at: 61 put: #('whileTrue:' 'SMB_whileTrue_');
	at: 62 put: #('writeAll:' 'SMB_writeAll_');
	at: 63 put: #('write:' 'SMB_write_');
	yourself