pharo-exporting
symbolDefintion
    <preventExport>
    "Auto generated Symbol definition from system/type/SymbolInitialization.ci
     Use the script at _meta/extractSymbols to generate this method"

    ^ #(
        ('=' 'SMB__equals_')
        ('==' 'SMB__pequals_')
        ('asString' 'SMB_asString')
        ('assignFor:to:' 'SMB_assignFor_to_')
        ('doesNotUnderstand:' 'SMB_doesNotUnderstand_')
        ('hash' 'SMB_hash')
        ('pinocchioReflective:' 'SMB_pinocchioReflective_')
    )