*Pinocchio
mainMenuItems
	"Answer the most important menu items available for this tool set"

	^ #(#('Class Browser' #openClassBrowser) #('Workspace' #openWorkspace) #('Test Runner' #openTestRunner) #('Monticello Browser' #openMonticelloBrowser) #('File Browser' #openFileList) #('Process Browser' #openProcessBrowser) #- #('Pinocchio Browser' #openPinocchioBrowser) #('Pinocchio Changed' #pinocchioExportChanges) #('Pinocchio All' #pinocchioExportAll))